### ISSUE TITLE
[feature request] implement alpha to text outlines

### ISSUE THREAD

**Issue by jclampy** [oomek/attractplus#26]
If you try to do an alpha 'fade in' on text that has an outline applied to it, It looks like the outline doesn't 'fade in'.
Text alpha doesn't effect the outline. Supposedly this is both while using Animate or Inertia to perform the alpha change.

A temporary work-around is to draw the text onto a surface first and then perform the alpha change to said layer.

**Comment by jclampy** [comment]
After further thought. Please if possible, make the choice of alpha effecting the text outline as ''togglable'.
Because, at the moment it can produce an interesting effect which may be useful in some scenarios.
A thick outline can look a bit like a 'text bubble' and then the text can 'fade in' to appear on it.
An example of the effect in images below, before text fades in and then afterwards:
![Before Text Fades In](https://user-images.githubusercontent.com/64625994/191867996-453cf62f-4de8-4c34-a0e9-5b4d22d89623.png)
![After Text Fades In](https://user-images.githubusercontent.com/64625994/191868009-38edfdbe-99c0-4094-9116-ccbe4b032b14.png)

**Comment by oomek** [comment]
Fixed in https://github.com/oomek/attractplus/commit/243645793b9d6daac8756e3784c97809b2c9305e
