### ISSUE TITLE
Hyperspin Themes issue

### ISSUE THREAD

**Issue by nikosrozos** [oomek/attractplus#27]
Hello,
attractplus 2.6.1 or 2.6.2 with Hyperspin media layout, displays only wheel and video of themes. 
I get black background and no artwork at all, while vanilla attract 2.6.1 or 2.6.2 display themes fine.
I got the same problem on Windows 10 and Linux machine (Groovy Arcade).
Any suggestions?

Thank you

**Comment by oomek** [comment]
Deprecated SWF support has been removed in Attract Mode +
Please look for alternatives with more modernly scripted animations like in Hyperspin Attraction.
