### ISSUE TITLE
MacOSx64 compiles, but create-pkg.sh fails

### ISSUE THREAD

**Issue by estefan3112** [oomek/attractplus#28]
UPDATE: It seems to me that you only need to accept the create-pkg.sh file from DJHAN's fork, because that one works. For testing purposes, I copied DJHAN's entire osx folder to your repository, and the script worked.

Hello, while the source builds nicely on an Intel Mac, the creation of the app bundle fails with the following error message:

cp: ../attract: No such file or directory
ERROR in ./create-pkg.sh : line 73 exit code 1

This is apparently because the cloned directory is called attract plus instead of attract. After correcting this, the script fails with the following error:

fatal: Not a valid object name v2.6.2^
fatal: ambiguous argument 'v2.6.2..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument '..v2.6.2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
env: python: No such file or directory
ERROR in ./create-pkg.sh : line 103 exit code 127

That one I could not figure out by myself.

Cheers!

**Comment by zpaolo11x** [comment]
The script create-pkg.sh is obsolete and doesn't work for the current builds AFAIK. The script that CI is using to build packages is appbuilder.sh.

On a side note, why you need to compile yourself, instead of using the pre-built artifacts?

**Comment by estefan3112** [comment]
Hello and thanks! I started compiling on my M1 Mac, as the x64 builds from your repository do not work. On Apple Silicon, your repository still does not compile, only DJHAN's for does. The osx folder, as amended by DJHAN, creates nice DMGs for both platforms, also x64 in your repository, that's I wanted to tell you. In case of Apple Silicon, own codesigining is required to have them run. Cheers!

**Comment by estefan3112** [comment]
Let's close this finally 😀
