### ISSUE TITLE
3.01 sometimes freezes if I'm scrolling fast through a list of titles.

### ISSUE THREAD

**Issue by joelsaacks** [oomek/attractplus#38]
3.01 sometimes freezes if I'm scrolling fast through a list of titles. 2.62 never had this issue

**Comment by oomek** [comment]
To better understand the problem I would need the following:
1. `last_run.log`
2. Does AM+ freeze on one particular layout, or on any layout?
3. Does the baseline AM nightly build also freeze, or is it working fine?
https://forum.attractmode.org/index.php?topic=2324.0

**Comment by joelsaacks** [comment]
1.  See attachment
  2.  Only that layout (At the Arcade Multi-Cab)
  3.  Works fine. Not a single crash. Easy to duplicate in attractmode plus

I've attached a pic of what happens. The rotation freezes, but the music continues playing. Then I get the error in pic2.png.
Don't understand the errors in last_run.log about the Wheel graphics. Those wheels show fine. I can also view those files perfectly in paint or any other package.

Thanks
Joel

------------------------------- ***@***.*** Joel Saacks -------------------------------
________________________________

**Comment by joelsaacks** [comment]
I seem to have discovered what the issue is

This config:
I'd changed it from 100 to 300.
If I switch it back to 100 the freezing stops.

image_cache_mbytes   100



------------------------------- ***@***.*** Joel Saacks -------------------------------
________________________________

**Comment by oomek** [comment]
Yes, image_cache_mbytes  > 100 is known to cause unpredictable results.
