### ISSUE TITLE
Binary and files location on macOS

### ISSUE THREAD

**Issue by zpaolo11x** [oomek/attractplus#4]
When running attractplus I get the following error message:

`Warning: Attract-Mode was compiled to look for its default configuration files in: /usr/local/share/attract/, which is not available.`

but there's no /usr/local/share/attract/ folder on macOS. When I install the current stable Attract Mode (2.6.1fix) it comes packaged as an "app" and all AM files and folders are in the "package bundle" which is located in: /Applications/Attract.app/Content/. 

Content/ folder structure is this:

-- config/ contains all the default files (default-display.cfg, etc) and folders of AM, like language/, intro/, modules/, shaders/ etc
-- libs/ contains libraries like libavcodec.58.54.100.dylib etc
-- MacOS/ contains the attract executable
-- Resources contains Attract.icns icon file
info.plist is a config file for the app bundle

There is another .attract folder in the user home folder that contains user space settings and folders like attract.am, window.am, emulators folder, romlists folder, plugins and modules installed by the user etc

I'm on macOS Big Sur 11.3.1 on a Late 2013 13" Retina MBP.

**Comment by substring** [comment]
Hi!

The MacOS thing is a little complicated for us to build automatically through the github CI. So far I couldn't build a proper .dmg (needs a buuuuuunch of dependencies to cross compile for MacOS + complicated integration if we want 10.x old MacOS compatibility, or just give all them up and go for native building on 10.15 and higher). I hope to find time (and patience, most of all) to get that fixed and update the issue. I don't own a Mac myself, makes things even more complicated ...

**Comment by zpaolo11x** [comment]
If I can provide any help with testing let me know, as far as macOS versions are concerned, since Catalina can run on macs from 1012 I think it's quite safe to compile for that. If it's easier to go the /usr/local/share route, it's not a problem, I can build such a folder structure and test from there. Is the .attract folder still supposed to exist?
