### ISSUE TITLE
“Attract-Mode Plus” will damage your computer. You should move it to the Trash.

### ISSUE THREAD

**Issue by ckrokosh** [oomek/attractplus#54]
I've been running Attract Mode Plus (3.06) on my MAC Studio M2 Max (Ventura) for almost a year with no problems. Yesterday I tried to run it and I get a pop up saying “Attract-Mode Plus” will damage your computer. You should move it to the Trash."

I tried redownloading but still had the same problem. I also tried an older version with no luck.

I tried sudo xattr -rd com.apple.quarantine .....

This stopped the error but the app won't open. Running from terminal i get the following error.

dyld[1479]: Library not loaded: @loader_path/../libs/libsfml-graphics.2.6.dylib
  Referenced from: <FB62AB9B-FCA2-3A65-82E6-FC26460AA5BC> /Applications/Attract-Mode Plus.app/Contents/MacOS/attractplus
  Reason: tried: '/Applications/Attract-Mode Plus.app/Contents/MacOS/../libs/libsfml-graphics.2.6.dylib' (code signature invalid in <1C122ECF-FFC2-366B-8168-7C4ED1BE983A> '/Applications/Attract-Mode Plus.app/Contents/libs/libsfml-graphics.2.6.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00088AB0, codeBlobSize=0x00005910), '/usr/local/lib/libsfml-graphics.2.6.dylib' (no such file), '/usr/lib/libsfml-graphics.2.6.dylib' (no such file, not in dyld cache)
zsh: abort      ./attractplus

Any help would be appreciated. Not sure if this is due to some new apple security feature...i did recently update Ventura to 13.6.3

**Comment by zpaolo11x** [comment]
It seems it doesn't like the way the code of SFML is signed, could you try ad-hoc signing it and see if it change anything? You should open a terminal, go to:

/Applications/Attract-Mode Plus.app/Contents/libs

and run this command to self sign the library:

codesign --force -s - libsfml-graphics.2.6.dylib

After that let's see if the error message changes...

**Comment by ckrokosh** [comment]
That worked but I had to do it for all files in the libs directory. Your command fixed the one file but then it just gave me the same error with a different file.

I used this command: codesign --force -s - lib*

Working fine now just weird that I have been using this file since 3.06 with no issues until yesterday.

**Comment by zpaolo11x** [comment]
Did you get the Apple Silicon bundle from the release page https://github.com/oomek/attractplus/releases/tag/3.0.6? That should be signed by a developer and it's strange that it gives issues. The self signing always work but only on your own machine, it shouldn't be necessary on the release bundle, so this needs to be investigated.

**Comment by ckrokosh** [comment]
Yes I got it from the release page. Not sure if its related but now if i double click the app it runs fine but it won't open retroarch. Other emulators open fine. If I run it from the command line retroarch works fine.

**Comment by portwally** [comment]
Same problem. Manual codesigning helped.

**Comment by zpaolo11x** [comment]
The root cause was identified: the dev certificate used for signing the previous releases has been revoked. We are working on fixing this with a new signing, for release 3.0.7

**Comment by estefan3112** [comment]
Hello, my apologies for the mess with the dev certificate.
Here is a newly signed version 3.0.7 for testing on Silicon Macs.
https://drive.google.com/file/d/19rSmZaTYqppZ1DGHE7IMBYsvNEDg2MvF/view?usp=drive_link
@ckrokosh - could I kindly ask you to check whether this app bundle works for you? 
Much appreciated.

**Comment by portwally** [comment]
Works, thanks!

**Comment by oomek** [comment]
Added to the 3.0.7 release page. Thanks.
