### ISSUE TITLE
bug after returning from pause?

### ISSUE THREAD

**Issue by pedrowarlock** [oomek/attractplus#55]
After entering the game, pause it, return to the menu, and open the game again. This bug happens and the system crashes

- Pause Hotkey pressed, sending SIGSTOP signal to process 3734
*** Resuming previously paused program, pid: 3734
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  9
  Current serial number in output stream:  11
Segmentation fault
pedrowarlock@DESKTOP-L45EAQG:/mnt/f/attractplus$

**Comment by oomek** [comment]
What's your platform? Does it happen on tha baseline Attract-Mode aswell?

**Comment by pedrowarlock** [comment]
> What's your platform? Does it happen on tha baseline Attract-Mode aswell?

WSL Ubuntu / running on windows 10

**Comment by oomek** [comment]
You are running It on wsl? Why don't you use the Windows binary?

**Comment by pedrowarlock** [comment]
> You are running It on wsl? Why don't you use the Windows binary?

I downloaded it clean to apply some changes to the source code

**Comment by oomek** [comment]
If you need a guide how to build for Windows on wsl let me know. The current compile.md is cery outdated.

**Comment by oomek** [comment]
Are you still having this problem? Have you tried on a normal system outside WSL?
