### ISSUE TITLE
Not Working on Raspberry pi OS (pi5) 64Bit

### ISSUE THREAD

**Issue by PittStone** [oomek/attractplus#57]
Not Working on Raspberry pi OS (pi5) 64Bit.
Would like to use attractplus on pi5 64Bit Bookworm.  But it doesnt start. 
Any Fix?

**Comment by oomek** [comment]
It's hard to guess the cause without a debug log.
Please run `attractplus --loglevel debug` and post last_run.log here

**Comment by PittStone** [comment]
It seems i can not execute it!

**Comment by oomek** [comment]
Paste the screenshot at least

**Comment by PittStone** [comment]
![Unbenannt](https://github.com/oomek/attractplus/assets/22426404/dc856758-f3f4-44a6-aa49-ae4b8eb302b7)

**Comment by PittStone** [comment]
![Unbenannt2](https://github.com/oomek/attractplus/assets/22426404/30857ab1-d996-4372-ab2c-dbee1f134328)

**Comment by oomek** [comment]
How did you install it?

**Comment by PittStone** [comment]
I have normal attract installed on retropie and copy'd the attractplus file only to the "bin" folder.

**Comment by oomek** [comment]
That's why you have issues.
Copy attractplus to `usr/local/bin`
The rest of the files to `usr/local/share/attract`

**Comment by PittStone** [comment]
Ok. i copy'd the files to your locations. But its the same. Nothings happen.

**Comment by oomek** [comment]
It's not a problem with attractplus but with your paths or permissions. Triplecheck everything again.

**Comment by PittStone** [comment]
attractplus: error while loading shared libraries: libavformat.so.58: cannot open shared object file: No such file or directory

**Comment by PittStone** [comment]
This?

cd ~/develop
git clone --depth 1 git://source.ffmpeg.org/ffmpeg.git
cd ffmpeg
./configure --enable-mmal --disable-debug --enable-shared
make
sudo make install
sudo ldconfig

**Comment by PittStone** [comment]
Or this full setup? 
https://pimylifeup.com/compiling-ffmpeg-raspberry-pi/

**Comment by oomek** [comment]
This is building ffmpeg not installing. It's going to take a while. Btw this is not a place to seek help with linux, but to report issues with attractmodeplus. I'm off to sleep, try to google it or jump on our discord server https://discord.gg/yNn9e5fb

**Comment by PittStone** [comment]
O.k. Thanks for your Help.
