### ISSUE TITLE
Default layout snap not used if video exists

### ISSUE THREAD

**Issue by Chadnaut** [oomek/attractplus#59]
```cpp
local a = fe.add_artwork("snap", 0, 0, 400, 400);
a.video_flags = Vid.ImagesOnly;

local t = fe.add_text("[Name]", 0, 0, 400, 400);
t.char_size = 30;
```

Emulator settings: snap contains two paths, one for images, one for videos.

Scenario 1:
- Image missing, video exists
- Default in snap folder only (ie: `../mame/snap/Mame.png`)
- Default is displayed

Scenario 2:
- Image missing, video exists
- Default in layout folder only (ie: `../layouts/my_layout/snap.png`)
- Default is NOT displayed <-- should behave as above?

Scenario 3:
- Snap missing, video missing
- Default in layout folder only (ie: `../layouts/my_layout/snap.png`)
- Default is displayed <-- only when ALL snap assets unavailable

Same behavior in AM 2.7.0

**Comment by oomek** [comment]
Check if this fixes the issue please:
https://github.com/oomek/attractplus/actions/runs/11196486552

**Comment by Chadnaut** [comment]
Looks good - the default snap in the layout folder is now used when a snap is missing, regardless if a video exits.
