### ISSUE TITLE
Missing image breaks vertex shaders

### ISSUE THREAD

**Issue by Chadnaut** [oomek/attractplus#64]
When an image fails to load (ie: no file) all subsequent object vertices change order.
This makes it impossible to use vertex shaders that rely on vertex order.

Normal: [tl, bl, tr, br]
Broken: [br, tl, bl, tr]

- Run example to see the expected behavior (a red square rotated left)
- Un-comment `bad_img` to see the vertices change order
- Leaving `bad_img` visible, un-comment a `fix` to see its results

Successfully adding another object appears to fix the broken ordering.
It seems something isn't getting cleaned up after a failed load.
    
layout.nut
```cpp
// local bad_img = fe.add_image("bad_name.png");
// local fix1 = fe.add_artwork("snap", 0, 0, 50, 50);
// local fix2 = fe.add_text("Maybe", 0, 0, 400, 50); // AM, not AM+
// local fix3 = fe.add_text("LongerText", 0, 0, 400, 50);

local img = fe.add_artwork("snap", 50, 50, 400, 400);
img.shader = fe.add_shader(Shader.VertexAndFragment, "shader.vert", "shader.frag");
```
shader.frag
```cpp
#version 120
uniform sampler2D texture;
void main() {
    gl_FragColor = gl_Color * vec4(1,0,0,1);
}
```
shader.vert
```cpp
#version 120
#extension GL_EXT_gpu_shader4 : require
void main() {
    vec2[4] offset = vec2[](vec2(0,50), vec2(50,0), vec2(-50,0), vec2(0,-50));
    gl_Position = gl_ModelViewProjectionMatrix * (gl_Vertex + vec4(offset[gl_VertexID % 4], 0.0, 0.0));
    gl_TexCoord[0] = gl_TextureMatrix[0] * gl_MultiTexCoord0;
    gl_FrontColor = gl_Color;
}
```

Attract-Mode Plus v3.0.8, Attract-Mode v2.7.0

**Comment by Chadnaut** [comment]
This issue appears to affect certain hardware and/or drivers:
- Affected NVIDIA Quadro T1000
- Unaffected NVIDIA GeForce GTX 960

**Comment by oomek** [comment]
Closing for now
