### ISSUE TITLE
gif animation refresh rate is not correct

### ISSUE THREAD

**Issue by kent79** [oomek/attractplus#74]
Hi oomek,

I bulit a jukebox theme. And find out video & sound not sync in version 2.7. So I would like to move AM+. The sync issue was fixed in your version, but gif animation (pachinko light effect) refresh rate is not correct, it is too fast. Do you have any idea and fix it. Thanks.

My jukebox theme
http://forum.attractmode.org/index.php?topic=4243.0

**Comment by oomek** [comment]
I don't think it's a problem with AM+. Quite the opposite, it's more optimized so it's better in gif playback.
According to photoshop frames of your flashing.gif have delays of 0.01s ( 10 ms )

**Comment by oomek** [comment]
![image](https://github.com/user-attachments/assets/cae803cf-0671-450d-8954-b51071eed3ff)

**Comment by kent79** [comment]
I try to change the setting of gif delay time, now is running fine both on AM & AM+. Since AM having video picture & sound not sync issue, I will shift it to AM+. Thank you.
