### ISSUE TITLE
Cannot convert the string

### ISSUE THREAD

**Issue by kent79** [oomek/attractplus#75]
Hi oomek,

I have a theme issue again. Is it a bug since there is no error ruuning on orginial AM. 

The action can run on AM+, but show error message. 

Thanks

AN ERROR HAS OCCURED [cannot convert the string]

CALLSTACK
*FUNCTION [on_signal()] layout.nut line [626]

LOCALS
[signal] "custom1"
[this] INSTANCE
Script Error in signal handler: on_signal - cannot convert the string

Below is my script 

`//Use with the 0-9 buttons to select music

class NumSearch
{
	_last_search="";
	_trigger="";

	constructor()
	{
		fe.add_signal_handler( this, "on_signal" )
		_trigger=fe.get_config()["trigger"].tolower();
	}

	function on_signal( signal )
	{
		if ( signal == _trigger )
		{
			_last_search=""
			_last_search = fe.overlay.edit_dialog(
				"Use with the 0-9 buttons to select music:",
				_last_search ).tointeger();

			if ( _last_search < fe.list.size + 1 )
					fe.list.index = _last_search - 1

			return true;
		}

		return false;
	}
}

NumSearch()
`

**Comment by kent79** [comment]
The issue should be coming from animate.nut file. I replace the AM nut file, the issue is gone

**Comment by kent79** [comment]
you can download the theme in here.  The error message will show on attractplus-console message while you press "custom1" key. Thanks

https://www.dropbox.com/scl/fi/fvmk671awus4s51m9gq0n/C.A.T-AM.zip?rlkey=lvr88auks0sh7mkz51tc3hzdl&dl=0

**Comment by oomek** [comment]
I am not getting any errors
![image](https://github.com/user-attachments/assets/64bac5e6-0bde-4949-a44e-af431b199f02)

**Comment by oomek** [comment]
As I said, it gives an error only when you enter an invalid character.
You should add some protection to only allow integers to be processed with `.tointeger()` method

**Comment by oomek** [comment]
Print to the console the output of `_last_search` after `fe.overlay.edit_dialog()` but before `.tointeger()`

**Comment by oomek** [comment]
```cpp
_last_search = fe.overlay.edit_dialog("Use with the 0-9 buttons to select music:", _last_search )
fe.log(_last_search);
_last_search = _last_search.tointeger();
```

**Comment by kent79** [comment]
Than 

> As I said, it gives an error only when you enter an invalid character. You should add some protection to only allow integers to be processed with .tointeger() method
> 
> Print to the console the output of `_last_search` after `fe.overlay.edit_dialog()` but before `.tointeger()`
> 
> ```c++
> _last_search = fe.overlay.edit_dialog("Use with the 0-9 buttons to select music:", _last_search)
> fe.log(_last_search);
> _last_search = _last_search.tointeger();
> ```

Thank you for coding, the error message is gone now.

One more question, Do you know how to change the font as above popup overlay?

On orginial AM, I can use fe.layout.font = "font/impact.ttf" to change it. But in AM+, it doesn't work. Please advise. Thanks.

**Comment by oomek** [comment]
Listen, this is not a layout coding helpdesk, but AM+ issue tracker.
You have not even explained what was causing this error  and just asked for another advise.
To get help in diagnosing your coding mistakes I encourage you to join our Discord server and ask there.
https://discord.gg/fg5w55Yh

**Comment by kent79** [comment]
Sorry about it and Thank you for your advise.
