### ISSUE TITLE
Layouts in .zip archives not in layout selection list

### ISSUE THREAD

**Issue by JetA2** [oomek/attractplus#76]
Hi, and thank you for your work on this project!

I've compiled version 3.0.9 on Arch Linux and the program runs fine.
However, layouts are not showing up in the layout selection list unless I unzip them.

The same layout zips show up on Attract Mode 2.7.0, is there a difference in functionality between AM and AM+ for this feature?

**Comment by oomek** [comment]
Loading layouts from zip was removed in Attract-Mode Plus
